# Builds a docker image, then tags it with the github sha and pushes it to our Amazon ECR registry

inputs:
  module-name:
    description: "Name of the module to build. Used as the default image name and src dir unless 'image-name' or 'src-path' are used."
    required: true
  build-for-environment:
    description: "The backend environment we are building for (API calls are pointed to).  This should be one of (development, staging, production)."
    required: true
  extra-build-args:
    description: "Extra args passed to 'docker build'."
    required: false
  src-path:
    description: "What folder to be (generally to find the Dockerfile in) default is root of repo"
    required: false


runs:
  using: 'composite'
  steps:
    - uses: ./.github/actions/setup-env
    # https://github.com/aws-actions/amazon-ecr-login
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - shell: bash
      run: |
        # Env var parsing
        INPUT_SRC_PATH=${{ inputs.src-path }}
        IMAGE_NAME=${{ inputs.module-name }}
        SRC_PATH=${INPUT_SRC_PATH:-"./"}
        REPO_IMAGE=${{ steps.login-ecr.outputs.registry }}/$IMAGE_NAME
        DOCKER_BUILDKIT=1
        ENVIRONMENT=${{ inputs.build-for-environment }}
        BRANCH_NAME=${{env.ENV_NAME}}
        IMAGE_TAG=$ENVIRONMENT-${{ env.SLUG }}

        # Create repo if needed
        aws ecr create-repository --repository-name $IMAGE_NAME || true # Just let this fail if the repo already exists

        # Grab our cached images, if present
        cd $SRC_PATH
        CACHE_FROM_ARGS="--cache-to type=local,dest=/mnt/shared/layercache,mode=max --cache-from type=local,src=/mnt/shared/layercache"
        BUILD_ARGS="--build-arg BUILD_FOR_ENVIRONMENT=$ENVIRONMENT --build-arg IMAGE_TAG=$IMAGE_TAG"

        # Finally, build our runner container
        echo "Running: \n    docker buildx build ${{ inputs.extra-build-args }} $BUILD_ARGS $CACHE_FROM_ARGS -t $REPO_IMAGE:$IMAGE_TAG -t $REPO_IMAGE:latest --push ."
        docker buildx build ${{ inputs.extra-build-args }} $BUILD_ARGS $CACHE_FROM_ARGS -t $REPO_IMAGE:$IMAGE_TAG -t $REPO_IMAGE:latest --push .